spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306/study?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul
    username: happycarrot
    password: jmh3385
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format_sql: false
    jackson:
      serialization:
        fail-on-empty-beans: false

springdoc:
  packages-to-scan: com.board.api
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /_api/v1
  swagger-ui:
    path: swagger-ui.html # http://localhost:8080/swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none

jwt:
  access-token-key: dskfjaskjfhkjhefjknxiu3q59534972y3499h